import {client,currentStudent,submitImages} from './cloud-client.js';
import {exportPages} from './handwriting-export.js';
const save=document.getElementById('saveImage'),submit=document.getElementById('submitWork'),note=document.getElementById('studentIdentity');
let student=null;
function status(text){note.textContent=text;}
async function refresh(){try{student=client?await currentStudent():null;if(!student){status('학생 입장 후 연습장을 선생님께 제출할 수 있어요.');return}status(`${student.classroom.name} · ${student.name}`);const text=document.getElementById('text'),prompt=student.classroom.practice_text||'';document.getElementById('practiceNotice').textContent=prompt?'선생님이 제시한 문구를 따라 써 주세요.':'자유 연습 · 쓰고 싶은 문구를 입력하세요.';if(prompt){text.value=prompt;text.readOnly=true;document.querySelectorAll('[data-sample],#reset').forEach(b=>b.disabled=true);text.dispatchEvent(new Event('input',{bubbles:true}));}if(student.classroom.practice_title){const title=document.getElementById('title');title.value=student.classroom.practice_title;title.dispatchEvent(new Event('input',{bubbles:true}));}document.getElementById('studentLink').textContent='내 제출물 · 피드백';document.getElementById('studentLink').href='student.html?view=submissions';document.getElementById('write').click();}catch{status('학생 입장 상태를 확인하지 못했어요. 다시 입장해 주세요.');}}
save.onclick=async()=>{save.disabled=true;try{const blobs=await exportPages();for(let i=0;i<blobs.length;i++){const url=URL.createObjectURL(blobs[i]),a=document.createElement('a');a.href=url;a.download=`또박또박-${i+1}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}status(`${blobs.length}장의 이미지를 저장했어요. 여러 장일 때 브라우저의 다운로드 허용이 필요할 수 있어요.`);}catch(error){status(error.message)}finally{save.disabled=false}};
submit.onclick=async()=>{
 if(!student){location.href='student.html';return;}
 const title=document.getElementById('title').value||'손글씨 연습';
 if(!confirm(`${student.classroom.name}의 ${student.name} 학생으로 현재 연습장을 제출할까요?`))return;
 submit.disabled=true;save.disabled=true;status('연습장을 이미지로 만들고 제출하고 있어요…');
 try{const images=await exportPages();await submitImages(student,title,images);status('제출했어요! 학생 페이지에서 선생님의 피드백을 확인하세요.');}catch(error){status(`제출 실패: ${error.message}`)}finally{submit.disabled=false;save.disabled=false}
};refresh();
const photoDialog=document.getElementById('photoDialog'),photoForm=document.getElementById('paperPhotoForm'),photoStatus=document.getElementById('paperPhotoStatus'),photoSend=document.getElementById('sendPaperPhotos');
let paperPhotos=[],photoBusy=false;
const photoControls=['takePaperPhoto','choosePaperPhotos','closePhotoSubmit'];
function drawPaperPhotos(){const area=document.getElementById('paperPhotoPreview');area.replaceChildren();paperPhotos.forEach((entry,i)=>{const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption'),remove=document.createElement('button');image.src=entry.url;image.alt=`제출할 연습장 사진 ${i+1}`;caption.textContent=`${i+1}번째 사진`;remove.type='button';remove.textContent='이 사진 빼기';remove.disabled=photoBusy;remove.onclick=()=>{URL.revokeObjectURL(entry.url);paperPhotos.splice(i,1);drawPaperPhotos();photoStatus.textContent=`${paperPhotos.length}장 선택했어요.`};figure.append(image,caption,remove);area.append(figure)});photoSend.disabled=photoBusy||!paperPhotos.length;photoControls.forEach(id=>document.getElementById(id).disabled=photoBusy)}
function clearPaperPhotos(){paperPhotos.forEach(entry=>URL.revokeObjectURL(entry.url));paperPhotos=[];drawPaperPhotos()}
function addPaperPhotos(input){const files=[...input.files];input.value='';if(!files.length||photoBusy)return;if(paperPhotos.length+files.length>20){photoStatus.textContent='사진은 최대 20장까지 제출할 수 있어요.';return}if(files.some(file=>!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)){photoStatus.textContent='한 장당 10MB 이하의 JPG, PNG, WebP 사진을 선택해 주세요. 다른 형식은 JPG로 저장한 뒤 선택해 주세요.';return}paperPhotos.push(...files.map(file=>({file,url:URL.createObjectURL(file)})));drawPaperPhotos();photoStatus.textContent=`${paperPhotos.length}장 선택했어요. 사진을 확인한 뒤 제출해 주세요.`}
document.getElementById('openPhotoSubmit').onclick=async()=>{try{student=client?await currentStudent():null;if(!student){location.href='student.html';return}document.getElementById('paperPhotoTitle').value=student.classroom.practice_title||document.getElementById('title').value||'종이 손글씨 연습';photoStatus.textContent='';photoDialog.showModal()}catch(error){status(error.message)}};
document.getElementById('takePaperPhoto').onclick=()=>document.getElementById('paperCamera').click();
document.getElementById('choosePaperPhotos').onclick=()=>document.getElementById('paperPhotos').click();
for(const id of ['paperCamera','paperPhotos'])document.getElementById(id).onchange=event=>addPaperPhotos(event.target);
document.getElementById('closePhotoSubmit').onclick=()=>photoDialog.close();
photoDialog.addEventListener('cancel',event=>{if(photoBusy)event.preventDefault()});photoDialog.addEventListener('close',clearPaperPhotos);
photoForm.onsubmit=async event=>{event.preventDefault();if(photoBusy||!paperPhotos.length)return;if(!photoForm.reportValidity())return;photoBusy=true;drawPaperPhotos();photoStatus.textContent='사진을 제출하고 있어요…';try{const activeStudent=await currentStudent();if(!activeStudent||activeStudent.id!==student.id)throw new Error('학생 입장 상태가 바뀌었어요. 다시 로그인해 주세요.');await submitImages(activeStudent,document.getElementById('paperPhotoTitle').value.trim(),paperPhotos.map(entry=>entry.file));photoBusy=false;photoDialog.close();status('종이에 쓴 연습장 사진을 제출했어요! 내 제출물 · 피드백에서 확인하세요.')}catch(error){photoStatus.textContent=`제출 실패: ${error.message}. 사진은 그대로 남아 있어요.`}finally{photoBusy=false;drawPaperPhotos()}};
