const {JSDOM}=require('jsdom');const esbuild=require('esbuild');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{
 const bundle=await esbuild.build({entryPoints:['portal.js'],bundle:true,write:false,format:'iife',plugins:[{name:'mock-cloud',setup(build){build.onResolve({filter:/cloud-client\.js$/},()=>({path:'mock-cloud',namespace:'test'}));build.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`export const client=window.TEST.client;export const checked=async p=>{const r=await p;if(r.error)throw r.error;return r.data};export const assertConfigured=()=>{};export const currentStudent=()=>window.TEST.student;export const submitImages=(...args)=>window.TEST.submit(...args);export const signedImage=async()=> 'data:image/png;base64,iVBORw0KGgo=';export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));`,loader:'js'}));}}]});
 const state={writing_classes:[{id:'class1',name:'6-1',code:'abcdef123456'}],writing_students:[{id:'student1',class_id:'class1',name:'첫 학생',number:1,active:true}],writing_submissions:[{id:'work1',student_id:'student1',title:'첫 연습',paths:['one.png'],feedback:'',reviewed_at:null,created_at:new Date().toISOString()}]};
 let seq=0,who={id:'teacher1',is_anonymous:false};
 function query(table){let filters=[],action='read',values=null;const q={select(){return q},order(){return q},eq(key,value){filters.push([key,value]);return q},insert(v){action='insert';values=v;return q},update(v){action='update';values=v;return q},single(){return run(true)},maybeSingle(){return run(true)},then(resolve,reject){return run(false).then(resolve,reject)}};
 async function run(single){let list=state[table].map(row=>table==='writing_submissions'?{...row,writing_students:state.writing_students.find(s=>s.id===row.student_id)}:row).filter(row=>filters.every(([key,value])=>key==='writing_students.class_id'?row.writing_students.class_id===value:row[key]===value));if(action==='insert'){const row={id:'new'+(++seq),code:'aabbccddeeff',...values};state[table].push(row);list=[row]}if(action==='update'){list.forEach(row=>Object.assign(state[table].find(x=>x.id===row.id),values));list=list.map(row=>({...row,...values}))}return{data:single?list[0]||null:list,error:null}}
 return q;}
 const client={auth:{getUser:async()=>({data:{user:who}}),getSession:async()=>({data:{session:{user:who}}}),signInWithPassword:async()=>({data:{}}),signUp:async()=>({data:{}}),signOut:async()=>({data:{}})},from:query,rpc:async(name,args)=>{
 if(name==='writing_is_teacher')return{data:true};
 if(name==='writing_add_student'){const id='student'+(++seq);state.writing_students.push({id,class_id:args.class_key,name:args.student_name,number:args.student_number,active:true});return{data:{id,code:'1234567890abcdef1234567890abcdef'}}}
 if(name==='writing_reset_student'){state.writing_students.find(s=>s.id===args.student_key).active=!args.disable;return{data:'fedcba0987654321fedcba0987654321'}}
 if(name==='writing_join')return{data:{}};
 throw new Error(name);
 }};
 const create=filename=>{const dom=new JSDOM(fs.readFileSync(filename,'utf8'),{url:'http://localhost/',runScripts:'outside-only'});dom.window.confirm=()=>true;dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new dom.window.Event('close'))};dom.window.TEST={client,student:null,submit:async()=>{}};return dom;};
 const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};
 const teacher=create('teacher.html');teacher.window.eval(bundle.outputFiles[0].text);await settle();const doc=teacher.window.document;
 assert.equal(doc.getElementById('dashboard').hidden,false);assert.match(doc.getElementById('roster').textContent,/첫 학생/);assert.equal(doc.getElementById('pendingCount').textContent,'1');
 function formSubmit(dom,id){const form=dom.window.document.getElementById(id);form.dispatchEvent(new dom.window.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:form.querySelector('button')}));}
 doc.getElementById('studentName').value='새 학생';doc.getElementById('studentNumber').value='2';formSubmit(teacher,'addStudent');await settle();assert.match(doc.getElementById('roster').textContent,/새 학생/);assert.match(doc.getElementById('issuedCode').textContent,/1234567890abcdef/);
 doc.querySelector('[data-edit="student1"]').click();doc.getElementById('editName').value='수정 학생';formSubmit(teacher,'editStudentForm');await settle();assert.match(doc.getElementById('roster').textContent,/수정 학생/);
 doc.querySelector('[data-review="work1"]').click();await settle();assert.equal(doc.getElementById('reviewDialog').open,true);assert.equal(doc.querySelectorAll('#reviewImages img').length,1);
 doc.getElementById('feedback').value='획을 또박또박 잘 썼어요.';formSubmit(teacher,'feedbackForm');await settle();assert.equal(state.writing_submissions[0].feedback,'획을 또박또박 잘 썼어요.');assert.equal(doc.getElementById('pendingCount').textContent,'0');
 doc.getElementById('search').value='없는 제출';doc.getElementById('search').dispatchEvent(new teacher.window.Event('input'));assert.equal(doc.querySelectorAll('[data-review]').length,0);
 doc.querySelector('[data-disable="student1"]').click();await settle();assert.equal(state.writing_students[0].active,false);assert.match(doc.getElementById('roster').textContent,/입장 중지/);
 who={id:'pupil1',is_anonymous:true};const pupil=create('student.html');pupil.window.TEST.student={...state.writing_students[0],userId:'pupil1',classroom:state.writing_classes[0]};let submitted=false;pupil.window.TEST.submit=async()=>{submitted=true};pupil.window.eval(bundle.outputFiles[0].text);await settle();const pd=pupil.window.document;
 assert.equal(pd.getElementById('studentHome').hidden,false);assert.match(pd.getElementById('mySubmissions').textContent,/획을 또박또박/);
 pd.getElementById('photoTitle').value='사진 연습';Object.defineProperty(pd.getElementById('photoFiles'),'files',{value:[new pupil.window.File(['test'],'photo.png',{type:'image/png'})]});formSubmit(pupil,'photoSubmit');await settle();assert.equal(submitted,true);assert.match(pd.getElementById('status').textContent,/제출했어요/);
 teacher.window.close();pupil.window.close();console.log('PASS: teacher roster add/edit/deactivate, submission search/review/feedback, student history/photo submission (mock client).');
})().catch(error=>{console.error(error);process.exitCode=1});
