const {JSDOM}=require('jsdom');const esbuild=require('esbuild');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{
 const bundle=await esbuild.build({entryPoints:['portal.js'],bundle:true,write:false,format:'iife',plugins:[{name:'mock-cloud',setup(build){build.onResolve({filter:/student-auth\.js$/},()=>({path:'mock-auth',namespace:'auth-test'}));build.onLoad({filter:/.*/,namespace:'auth-test'},()=>({contents:'export const studentPasswordAuth=(...args)=>window.TEST.login(...args);',loader:'js'}));build.onResolve({filter:/cloud-client\.js$/},()=>({path:'mock-cloud',namespace:'test'}));build.onLoad({filter:/.*/,namespace:'test'},()=>({contents:`export const client=window.TEST.client;export const checked=async p=>{const r=await p;if(r.error)throw r.error;return r.data};export const assertConfigured=()=>{};export const currentStudent=()=>window.TEST.student;export const submitImages=(...args)=>window.TEST.submit(...args);export const signedImage=async()=> 'data:image/png;base64,iVBORw0KGgo=';export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));`,loader:'js'}));}}]});
 const state={writing_classes:[{id:'class1',name:'6-1',code:'abcdef123456'}],writing_students:[{id:'student1',class_id:'class1',name:'첫 학생',number:1,active:true}],writing_submissions:[{id:'work1',student_id:'student1',title:'첫 연습',paths:['one.png'],feedback:'',reviewed_at:null,created_at:new Date().toISOString()}]};
 let seq=0,who={id:'teacher1',is_anonymous:false};
 function query(table){let filters=[],action='read',values=null;const q={select(){return q},order(){return q},eq(key,value){filters.push([key,value]);return q},insert(v){action='insert';values=v;return q},update(v){action='update';values=v;return q},single(){return run(true)},maybeSingle(){return run(true)},then(resolve,reject){return run(false).then(resolve,reject)}};
 async function run(single){let list=state[table].map(row=>table==='writing_submissions'?{...row,writing_students:state.writing_students.find(s=>s.id===row.student_id)}:row).filter(row=>filters.every(([key,value])=>key==='writing_students.class_id'?row.writing_students.class_id===value:row[key]===value));if(action==='insert'){const row={id:'new'+(++seq),code:'aabbccddeeff',...values};state[table].push(row);list=[row]}if(action==='update'){list.forEach(row=>Object.assign(state[table].find(x=>x.id===row.id),values));list=list.map(row=>({...row,...values}))}return{data:single?list[0]||null:list,error:null}}
 return q;}
 const client={auth:{getUser:async()=>({data:{user:who}}),getSession:async()=>({data:{session:who?{user:who}:null}}),signInWithPassword:async()=>({data:{}}),signUp:async()=>({data:{}}),signOut:async()=>({data:{}})},from:query,rpc:async(name,args)=>{
 if(name==='writing_is_teacher')return{data:who?.id==='teacher1'};
 if(name==='writing_student_logins')return{data:[{student_id:'student1',login_name:'첫 학생'}]};
 if(name==='writing_add_student'){const id='student'+(++seq);state.writing_students.push({id,class_id:args.class_key,name:args.student_name,number:args.student_number,active:true});return{data:{id,code:'1234567890abcdef1234567890abcdef'}}}
 if(name==='writing_set_student_active'){state.writing_students.find(s=>s.id===args.student_key).active=args.enabled;return{data:null}}
 if(name==='writing_join')return{data:{}};
 throw new Error(name);
 }};
 const create=filename=>{const dom=new JSDOM(fs.readFileSync(filename,'utf8'),{url:'http://localhost/?view=submissions',runScripts:'outside-only'});dom.window.confirm=()=>true;dom.window.HTMLDialogElement.prototype.showModal=function(){this.open=true};dom.window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new dom.window.Event('close'))};dom.window.TEST={client,student:null,submit:async()=>{}};return dom;};
 const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};
 const teacher=create('teacher.html');teacher.window.eval(bundle.outputFiles[0].text);await settle();const doc=teacher.window.document;
 assert.equal(doc.getElementById('dashboard').hidden,false);assert.doesNotMatch(doc.getElementById('roster').textContent,/1번/);assert.match(doc.getElementById('roster').textContent,/첫 학생/);assert.equal(doc.getElementById('pendingCount').textContent,'1');
 function formSubmit(dom,id){const form=dom.window.document.getElementById(id);form.dispatchEvent(new dom.window.SubmitEvent('submit',{bubbles:true,cancelable:true,submitter:form.querySelector('button')}));}
 doc.getElementById('practiceText').value='오늘도 또박또박';formSubmit(teacher,'practiceForm');await settle();assert.equal(state.writing_classes[0].practice_text,'오늘도 또박또박');
 doc.getElementById('practiceText').value='';formSubmit(teacher,'practiceForm');await settle();assert.equal(state.writing_classes[0].practice_text,'');
 assert.match(doc.getElementById('roster').textContent,/로그인 이름: 첫 학생/);
 doc.querySelector('[data-edit="student1"]').click();doc.getElementById('editName').value='수정 학생';formSubmit(teacher,'editStudentForm');await settle();assert.match(doc.getElementById('roster').textContent,/수정 학생/);
 doc.querySelector('[data-review="work1"]').click();await settle();assert.equal(doc.getElementById('reviewDialog').open,true);assert.equal(doc.querySelectorAll('#reviewImages img').length,1);
 doc.getElementById('feedback').value='획을 또박또박 잘 썼어요.';formSubmit(teacher,'feedbackForm');await settle();assert.equal(state.writing_submissions[0].feedback,'획을 또박또박 잘 썼어요.');assert.equal(doc.getElementById('pendingCount').textContent,'0');
 doc.getElementById('search').value='없는 제출';doc.getElementById('search').dispatchEvent(new teacher.window.Event('input'));assert.equal(doc.querySelectorAll('[data-review]').length,0);
 doc.querySelector('[data-active="student1"]').click();await settle();assert.equal(state.writing_students[0].active,false);assert.match(doc.getElementById('roster').textContent,/입장 중지/);
 doc.querySelector('[data-active="student1"]').click();await settle();assert.equal(state.writing_students[0].active,true);
 who={id:'pupil1',is_anonymous:true};const pupil=create('student.html');pupil.window.TEST.student={...state.writing_students[0],userId:'pupil1',classroom:state.writing_classes[0]};let submitted=false;pupil.window.TEST.submit=async()=>{submitted=true};pupil.window.eval(bundle.outputFiles[0].text);await settle();const pd=pupil.window.document;
 assert.equal(pd.getElementById('studentHome').hidden,false);assert.match(pd.getElementById('mySubmissions').textContent,/획을 또박또박/);
 pd.getElementById('photoTitle').value='사진 연습';Object.defineProperty(pd.getElementById('photoFiles'),'files',{value:[new pupil.window.File(['test'],'photo.png',{type:'image/png'})]});formSubmit(pupil,'photoSubmit');await settle();assert.equal(submitted,true);assert.match(pd.getElementById('status').textContent,/제출했어요/);
 who=null;const newcomer=create('student.html');let loginCalls=[];newcomer.window.TEST.login=async(...args)=>{loginCalls.push(args);who={id:'new-pupil',is_anonymous:false};newcomer.window.TEST.student={...state.writing_students[0],userId:'new-pupil',classroom:state.writing_classes[0]}};
 newcomer.window.eval(bundle.outputFiles[0].text);await settle();const nd=newcomer.window.document;
 assert.equal(nd.getElementById('classCodeField').hidden,false);assert.equal(nd.getElementById('joinClass').required,true);
 nd.getElementById('loginName').value='내 이름';nd.getElementById('loginPassword').value='test-password';nd.getElementById('confirmPassword').value='different';nd.getElementById('joinClass').value='abcdef123456';formSubmit(newcomer,'studentLogin');await settle();assert.equal(loginCalls.length,0);assert.match(nd.getElementById('status').textContent,/같지 않아요/);
 nd.getElementById('confirmPassword').value='test-password';formSubmit(newcomer,'studentLogin');await settle();assert.deepEqual(loginCalls[0],['register','내 이름','test-password','abcdef123456']);assert.equal(nd.getElementById('studentHome').hidden,false);assert.equal(nd.getElementById('loginPassword').value,'');assert.equal(newcomer.window.localStorage.getItem('ttobak-student-name'),'내 이름');assert.equal(newcomer.window.localStorage.getItem('password'),null);
 who=null;const returning=create('student.html');returning.window.TEST.login=async(...args)=>{loginCalls.push(args);who={id:'new-pupil',is_anonymous:false};returning.window.TEST.student={...state.writing_students[0],userId:'new-pupil',classroom:state.writing_classes[0]}};returning.window.localStorage.setItem('ttobak-student-name','내 이름');returning.window.eval(bundle.outputFiles[0].text);await settle();const rd=returning.window.document;
 assert.equal(rd.getElementById('classCodeField').hidden,true);assert.equal(rd.getElementById('joinClass').required,false);assert.equal(rd.getElementById('confirmPassword').required,false);rd.getElementById('loginPassword').value='test-password';formSubmit(returning,'studentLogin');await settle();assert.equal(loginCalls.at(-1)[0],'login');assert.equal(rd.getElementById('studentHome').hidden,false);
 teacher.window.close();pupil.window.close();newcomer.window.close();returning.window.close();console.log('PASS: teacher management and feedback, student photo submission, first registration, password confirmation and returning name/password login (mock client).');
})().catch(error=>{console.error(error);process.exitCode=1});
